spring:
  application:
    name: sugram
  datasource:
    url: jdbc:postgresql://dpg-cseecce8ii6s739257pg-a/post_db_zkm9
    username: post_user
    password: fNJxJUGs4mbCl88SIQ5D1a7UFFy25het
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
my_token:
  key: shaxobiddindevjknsjnvfwefbnwujnosdwssedfwef
  expire_time: 86400000
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE